apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev-cluster
servers: 1
agents: 2
kubeAPI:
  host: "master.127.0.0.1.nip.io"
  hostIP: "127.0.0.1"
  hostPort: "6445"
image: 'docker.io/rancher/k3s:v1.28.8-k3s1'
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "360s"
  k3s:
    extraArgs:
      - arg: --tls-san=devcluster.localhost
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
registries:
  create:
    name: 'registry.localhost'
    host: '0.0.0.0'
    hostPort: '5000'